// @agent: cloudflare-backend
// Audit logging types and enums

export enum AuditEventType {
  // Authentication events
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_TOKEN_REFRESH = 'AUTH_TOKEN_REFRESH',
  AUTH_SESSION_CREATED = 'AUTH_SESSION_CREATED',
  AUTH_SESSION_DESTROYED = 'AUTH_SESSION_DESTROYED',
  AUTH_SESSION_VALIDATED = 'AUTH_SESSION_VALIDATED',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_SESSION_INVALID = 'AUTH_SESSION_INVALID',
  AUTH_SESSION_ACCESS = 'AUTH_SESSION_ACCESS',
  AUTH_FLOW_INITIATED = 'AUTH_FLOW_INITIATED',
  
  // State management events
  STATE_CREATED = 'STATE_CREATED',
  STATE_VALIDATED = 'STATE_VALIDATED',
  STATE_DELETED = 'STATE_DELETED',
  STATE_INVALID = 'STATE_INVALID',
  
  // Data access events
  DATA_ACCESS_READ = 'DATA_ACCESS_READ',
  DATA_ACCESS_WRITE = 'DATA_ACCESS_WRITE',
  DATA_ACCESS_DELETE = 'DATA_ACCESS_DELETE',
  DATA_ACCESS_DENIED = 'DATA_ACCESS_DENIED',
  
  // Data security events
  DATA_ENCRYPTION = 'DATA_ENCRYPTION',
  DATA_DECRYPTION = 'DATA_DECRYPTION',
  
  // Security events
  SECURITY_SUSPICIOUS_ACTIVITY = 'SECURITY_SUSPICIOUS_ACTIVITY',
  SECURITY_RATE_LIMIT_EXCEEDED = 'SECURITY_RATE_LIMIT_EXCEEDED',
  CORS_VIOLATION = 'CORS_VIOLATION',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  
  // API operation events
  API_CALL_FAILED = 'API_CALL_FAILED',
  API_CALL_SUCCESS = 'API_CALL_SUCCESS',
  
  // General request events
  REQUEST_ERROR = 'REQUEST_ERROR',
  REQUEST_RECEIVED = 'REQUEST_RECEIVED',
  
  // URL generation events
  URL_GENERATED = 'URL_GENERATED',
  
  // PKCE events
  PKCE_CHALLENGE_CREATED = 'PKCE_CHALLENGE_CREATED',
  PKCE_VERIFIER_CREATED = 'PKCE_VERIFIER_CREATED',
  PKCE_VERIFICATION_SUCCESS = 'PKCE_VERIFICATION_SUCCESS',
  PKCE_VERIFICATION_FAILURE = 'PKCE_VERIFICATION_FAILURE',
  PKCE_FLOW_COMPLETED = 'PKCE_FLOW_COMPLETED',
  PKCE_CHALLENGE_STORED = 'PKCE_CHALLENGE_STORED',
  PKCE_CHALLENGE_STORE_FAILURE = 'PKCE_CHALLENGE_STORE_FAILURE',
}

export enum LogLevel {
  INFO = 'INFO',
  WARN = 'WARN',
  ERROR = 'ERROR',
}

export interface AuditLogEntry {
  timestamp: string;
  eventType: AuditEventType;
  level: LogLevel;
  userId?: string;
  sessionId?: string;
  correlationId: string;
  ipAddress?: string;
  userAgent?: string;
  resource?: string;
  action?: string;
  result: 'success' | 'failure';
  metadata?: Record<string, any>;
}