name = "prompted-blog-worker"
main = "src/oauth-google/index.ts"
compatibility_date = "2024-01-01"

[vars]
REDIRECT_URI = "https://promptedblog.com/oauth/google/callback"

[[kv_namespaces]]
binding = "OAUTH_STATE"
id = "859004e0bdaa4d05adf0e16174bc2c82"
